# Generated by Django 4.0.1 on 2022-01-19 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 17, 28, 26, 29791)),
        ),
    ]
